feat: add prisma adapter
nextauthjs/adapters pull request #1
Opened 2021-01-25 09:02 UTC by williamluke4

2021-01-26 23:09 UTC, balazsorban44 requested changes
Just some formatting suggestions, looks good otherwise! Thanks!

2021-01-26 23:09 UTC, balazsorban44 commented on packages/prisma/src/index.ts
> +      accessTokenExpires: string | Date | null | undefined
```suggestion
      accessTokenExpires?: string | Date | null
```

2021-01-26 23:09 UTC, balazsorban44 commented on packages/prisma/src/index.ts
> +        if (session && session.expires && new Date() > session.expires) {
```suggestion
        if (session?.expires && new Date() > session.expires) {
```

2021-01-26 23:09 UTC, balazsorban44 commented on packages/prisma/src/index.ts
> +        return updatedSession;
```suggestion
        return prisma[Session as "session"].update({
          where: { id },
          data: { expires },
        })
```

2021-01-26 23:09 UTC, balazsorban44 commented on packages/prisma/src/index.ts
> +        });
```suggestion
        return prisma[Session as "session"].delete({
          where: { sessionToken },
        });
```

2021-01-26 23:09 UTC, balazsorban44 commented on packages/prisma/src/index.ts
> +          new Date() > verificationRequest.expires
```suggestion
          verificationRequest?.expires &&
          new Date() > verificationRequest.expires
```

2021-01-26 23:09 UTC, balazsorban44 commented on packages/prisma/src/index.ts
> +        });
```suggestion
        return prisma[VerificationRequest as "verificationRequest"].delete({
          where: { token: hashedToken },
        });
```

2021-01-26 23:09 UTC, balazsorban44 commented on packages/prisma/src/index.ts
> +    });
```suggestion
    return {
      createUser,
      getUser,
      getUserByEmail,
      getUserByProviderAccountId,
      updateUser,
      deleteUser,
      linkAccount,
      unlinkAccount,
      createSession,
      getSession,
      updateSession,
      deleteSession,
      createVerificationRequest,
      getVerificationRequest,
      deleteVerificationRequest,
    }
```

2021-01-26 23:09 UTC, balazsorban44 commented on packages/prisma/src/index.ts
> +        return updatedSession;
```suggestion
        return prisma[Session as "session"].update({
          where: { id },
          data: { expires },
        })
```

2021-01-26 23:09 UTC, balazsorban44 commented on packages/prisma/src/index.ts
> +        if (session && session.expires && new Date() > session.expires) {
```suggestion
        if (session?.expires && new Date() > session.expires) {
```

2021-01-26 23:09 UTC, balazsorban44 commented on packages/prisma/src/index.ts
> +        });
```suggestion
        return prisma[Account as "account"].create({
          data: {
            accessToken,
            refreshToken,
            providerAccountId: `${providerAccountId}`,
            providerId,
            providerType,
            accessTokenExpires,
            user: { connect: { id: userId } },
          },
        });
```

2021-01-27 08:53 UTC, williamluke4 commented on packages/prisma/src/index.ts
> +      : 0;
Here shouldn't the  `defaultSessionMaxAge` && `appOptions?.session?.maxAge` remain as ms, not seconds.

2021-01-27 09:21 UTC, balazsorban44 approved these changes
LGTM!

2021-01-27 09:22 UTC, merged