Updated DynamoDB Adaptor documentation
nextauthjs/adapters pull request #126
Opened 2021-06-03 16:06 UTC by manishprivet

## Reasoning 💡
#90 changed the way DynamoDB was implemented, and the documentation needed to be updated accordingly.

## Checklist 🧢

- [x] Documentation
- [ ] Tests
- [ ] Ready to be merged

## Affected issues 🎟
Addresses #125

2021-06-04 00:06 UTC, balazsorban44 requested changes
So in the source I see that table name has a default value, so it is actually not needed for a default setup. It defaults to `"next-auth" `

2021-06-04 00:09 UTC, balazsorban44 requested changes

2021-06-04 00:09 UTC, balazsorban44 commented on packages/dynamodb/README.md
> +You need to pass `DocumentClient` from `aws-sdk` to the adapter in addition to the table name.
Same as https://github.com/nextauthjs/next-auth/pull/2125#discussion_r645206437

2021-06-04 20:49 UTC, balazsorban44 requested changes
I would rather not mention table name this way, just show the bare minimal implementation, and maybe add an options section in the docs, under schema for example.

2021-06-07 17:29 UTC, ndom91 commented
Looks good to me!

2021-06-07 18:30 UTC, merged

2021-06-23 08:15 UTC, stephankaag commented
Hi @manishprivet 

With the current table design sessions cannot be looked up with the session's AccessToken. Is that on purpose? If so: what's the point of the AccessToken?

2021-06-23 08:19 UTC, manishprivet commented
> Hi @manishprivet 
> 
> With the current table design sessions cannot be looked up with the session's AccessToken. Is that on purpose? If so: what's the point of the AccessToken?

I didn't work on the table design actually. I think @PolMrt could answer your question