feat: add build step to package.json
nextauthjs/adapters pull request #148
Opened 2021-06-27 01:20 UTC by ndom91

## Reasoning 💡

Added missing build step to `fauna` adapter.

```
build: 'babel src --out-dir dist'
```

Also defined `"type": "module"` in the package.json.

## Checklist 🧢

- [ ] Documentation
- [ ] Tests
- [ ] Ready to be merged

## Affected issues 🎟

Closes #145

2021-06-27 16:25 UTC, balazsorban44 approved these changes

2021-06-27 16:26 UTC, balazsorban44 requested changes
This will need a `.babelrc.js` config like this: https://github.com/nextauthjs/adapters/blob/main/packages/typeorm-legacy/.babelrc.js

2021-06-27 18:41 UTC, ndom91 commented
> This will need a `.babelrc.js` config like this: https://github.com/nextauthjs/adapters/blob/main/packages/typeorm-legacy/.babelrc.js

The `fauna` subdirectory already has one apparently

2021-06-28 01:07 UTC, balazsorban44 approved these changes

2021-06-28 01:07 UTC, merged