Add sequelize adapter
nextauthjs/adapters pull request #73
Opened 2021-04-28 14:58 UTC by EXIT-ALAMERY

Added the adapter for Sequelize ORM.

2021-04-28 19:02 UTC, balazsorban44 requested changes
Thank you so much for submitting this! I had some comments, but all in all it looks great so far!

PS.: If you are into TypeScript (totally fine if you are not interested), we now have an `Adapter` interface, that could help you type the whole adapter, by applying the interface on the Adapter function.

https://github.com/nextauthjs/next-auth/blob/0cf1823e70ce48024362670d19db09fc0bbb9727/types/adapters.d.ts#L74-L125

2021-04-29 16:23 UTC, balazsorban44 requested changes

2021-04-29 16:23 UTC, balazsorban44 commented on packages/sequelize/src/adapter/index.js
> +import { CreateUserError } from "./lib/errors";
```suggestion
import { CreateUserError } from "next-auth/errors";
```

These are included in the base library now. check out the content of the errors module, there are more type of errors as well. You can delete the `./lib/errors` file now

2021-04-29 16:23 UTC, balazsorban44 commented on packages/sequelize/src/adapter/index.js
> +import logger from "./lib/logger";
```suggestion
```

You will find this in `appOptions` in `getAdapter`. You can remove `./lib/logger`

2021-04-29 16:23 UTC, balazsorban44 commented on packages/sequelize/src/adapter/index.js
> +    function debug(debugCode, ...args) {
```suggestion
    const logger = appOptions.logger
    function debug(debugCode, ...args) {
```

2021-05-13 05:11 UTC, luke-j reviewed
Nice work, would be great to get this in.

2021-05-13 05:11 UTC, luke-j commented on packages/sequelize/example/db/models/index.js
> +} from 'next-auth-sequelize-adapter/models';
```suggestion
} from '@next-auth/sequelize-adapter';
```

2021-05-13 05:11 UTC, luke-j commented on packages/sequelize/example/db/models/index.js
> +const basename = path.basename(__filename);
Not used

```suggestion
```

2021-05-13 05:11 UTC, luke-j commented on packages/sequelize/example/db/models/user_extended.js
> +import { userSchema } from "next-auth-sequelize-adapter";
```suggestion
import { userSchema } from "@next-auth/sequelize-adapter";
```

2021-05-13 05:11 UTC, luke-j commented on packages/sequelize/example/pages/api/auth/[...nextauth].js
> +import { SequelizeAdapter } from "next-auth-sequelize-adapter";
```suggestion
import { SequelizeAdapter } from "@next-auth/sequelize-adapter";
```

2021-05-13 05:11 UTC, luke-j commented on packages/sequelize/package.json
> +}
This should have a peer dependency on sequelize, right?

2021-05-24 15:09 UTC, ndom91 commented
@EXIT-ALAMERY we now have official [TS types](https://github.com/nextauthjs/next-auth/blob/main/types/adapters.d.ts) for the adapters as well as a test suite all adapters should pass. Maybe these can help you finalize this adapter.

If you're still interested in getting this sequelize adapter in, I'd suggest checking out the suggestions made above and then maybe checking out the new [`basic-tests.ts`](https://github.com/nextauthjs/adapters/blob/canary/basic-tests.ts) file and get your seqeulize adapter passing :+1: 

Looking forward to this!

2021-05-24 15:16 UTC, balazsorban44 commented
@ndom91 I have talked to @EXIT-ALAMERY and unfortunately he doesn't have the opportunity to finish this up, so I am going to take this PR once I have the time.

2021-06-07 14:54 UTC, ndom91 commented
Hey guys this is looking awesome! If you can add the basic tests to this package i'd be comfortable merging and releasing a canary version!

See:
- Basic Test: https://github.com/nextauthjs/adapters/blob/canary/basic-tests.ts
- Prisma Example: https://github.com/nextauthjs/adapters/blob/canary/packages/prisma/tests/index.test.ts

2021-06-09 07:56 UTC, EXIT-ALAMERY commented
The tests for PostgreSQL passed successfully. I'll probably write tests for MySQL or MSSQL tomorrow.

![test](https://user-images.githubusercontent.com/69214549/121314969-54476180-c921-11eb-8919-66e956d57b00.jpg)

2021-06-09 09:03 UTC, ndom91 commented
Awesome thanks a lot!

2021-06-11 20:05 UTC, ndom91 commented
Tests for MySQL and Postgresql are in. Thanks guys! Is this alright to merge from your perspective?

Btw you still need to add sequelize to the adapter matrix in `.github/workflows/canary.yml`. 

Thanks!

2021-06-20 14:05 UTC, ndom91 commented
Hey guys I was taking a look at the tests, they don't seem to pass in CI, but that makes sense since yuo don't have any script or any way to setup the db in a CI environment. The `yarn test` script just executes `jest`. I assume in your local environment you manully created the docker container with the mysql db, seeded it, etc. right?

We need to come up with a shell script to automate that whole process in CI for both mysql and postgres. I'll try to push something here shortly :+1:

2021-06-20 14:44 UTC, ndom91 commented
So I cleaned up some of the default usernames / etc to make them match to what we usually use. Next, I added some npm scripts for each mysql and postgres to execute a bash script to setup the respective containers and execute jest tests on them once they're up.

Also none of the db drivers were listed as peerDeps or anything like that, so I added them as optional peerDeps for mysql and postgres.

Both test (mysql + postgres) pass now locally for me, starting from 0, building the containers, running migrations, running tests, etc. However on both tests I still have a ton of console.log output from what looks like the sequelize adapter itself, but I couldn't find any `console.log`'s anywhere. Do you have any idea where they're coming from? Haha

What do you think?

2021-06-22 16:50 UTC, EXIT-ALAMERY commented
The SQL queries you see in the console get generated by the sequelize library itself so, you can disable them by setting `logging: false` in the config file.

Also, I've seen the [sequelize-typescript](https://www.npmjs.com/package/sequelize-typescript) module but, the sequelize team doesn't officially maintain it. So, I decided not to implement it but, if you believe that proceeding with it would suffice the needs of this project, then I'll take a thorough look.

Thanks!

2021-06-22 20:52 UTC, ndom91 commented
> The SQL queries you see in the console get generated by the sequelize library itself so, you can disable them by setting `logging: false` in the config file.
> 
> Also, I've seen the [sequelize-typescript](https://www.npmjs.com/package/sequelize-typescript) module but, the sequelize team doesn't officially maintain it. So, I decided not to implement it but, if you believe that proceeding with it would suffice the needs of this project, then I'll take a thorough look.
> 
> Thanks!

I only mention it because the tests seem to be failing due to missing types. I did some testing with manually declare a dummy sequelize module, but that didn't seem to help.. 

@lluia any idea whats missing here? Checkout the latest failing test.

2021-06-30 13:46 UTC, EXIT-ALAMERY commented
We can try adding sequelize as a dependency and see if it works because I created full-fledged sequelize models specifically for the tests, so they're trying to import sequelize from the node modules, which doesn't exist.

2021-09-18 17:09 UTC, EXIT-ALAMERY commented
> Hey @EXIT-ALAMERY, we've done a major rewrite of the adapter API to simplify things significantly. Are you still interested in getting sequelize over the finish line?

That sounds great and, I wish all the best to nextauthjs, but, unfortunately, I am no longer interested in the sequelize adapter. Thank you for your patience and support.

2021-09-18 17:09 UTC, closed without merging

2021-09-18 17:57 UTC, balazsorban44 commented
no problem! we might reuse your code when we get some time to add a sequelize adapter! thank you!