feat(typeorm-legacy): custom user fields
nextauthjs/adapters pull request #87
Opened 2021-05-06 15:46 UTC by g10

2021-05-10 22:02 UTC, balazsorban44 requested changes
Thank you! I left a small suggestions. Also for this to work, please fix the merge conflicts by merging the `canary` branch into your own. This adapter has recently been simplified

2021-05-10 22:02 UTC, balazsorban44 commented on packages/typeorm-legacy/src/models/user.js
> +    this.emailVerified = profile?.emailVerified ? new Date() : undefined
```suggestion
  constructor(profile) {
    this.name = profile?.name
    this.email = profile?.email
    this.image = profile?.image
    this.emailVerified = profile?.emailVerified && new Date()
```

2021-05-23 20:17 UTC, limal commented
This is a must needed addition to custom models in NextAuth.js.

The current `phoneNumber` [tutorial](https://next-auth.js.org/tutorials/typeorm-custom-models) is not helpful as `phoneNumber` is not passed with a profile.

2021-05-24 15:13 UTC, balazsorban44 approved these changes

2021-05-24 15:18 UTC, balazsorban44 commented
Thanks for the PR! Seems that there is some problem with publishing. Once we figure that out, I think it is good to go!

2021-05-24 23:12 UTC, merged